### ISSUE TITLE
GraphvizException: TypeError: Module.print... is an inappropriate error message for what seems to be "graph too large for memory"

### ISSUE THREAD

**Issue by jzwolak** [Chentai-Kao/call-graph-plugin#15]
There is an earlier issue that mentions this and the issue was marked as resolved. I raise the issue again with a different point of view and call for a different resolution.

The following exception seems to be a result of the call graph being too large to display - possibly because of memory constraints. If this is true, then a suitable error message should be displayed to the user indicating that the call graph is too large and the scope should be reduced. In addition, some indications on how to reduce the scope should be suggested; or at least, a pointer to the documentation where the user may read and learn how to reduce the scope.

```
guru.nidi.graphviz.engine.GraphvizException: TypeError: Module.print is not a function
	at guru.nidi.graphviz.engine.ResultHandler.waitFor(ResultHandler.java:42)
	at guru.nidi.graphviz.engine.GraphvizV8Engine$Env.execute(GraphvizV8Engine.java:91)
	at guru.nidi.graphviz.engine.GraphvizV8Engine.jsExecute(GraphvizV8Engine.java:67)
	at guru.nidi.graphviz.engine.AbstractJsGraphvizEngine.execute(AbstractJsGraphvizEngine.java:28)
	at guru.nidi.graphviz.engine.Graphviz.execute(Graphviz.java:184)
	at guru.nidi.graphviz.engine.Renderer.toString(Renderer.java:46)
	at callgraph.Utils.getLayoutFromGraphViz(Utils.kt:300)
	at callgraph.Utils.layout(Utils.kt:115)
	at callgraph.CanvasBuilder.buildGraph(CanvasBuilder.kt:39)
	at callgraph.CanvasBuilder.build(CanvasBuilder.kt:27)
	at callgraph.CallGraphToolWindow$run$1.run(CallGraphToolWindow.kt:217)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:869)
	at callgraph.Utils$runBackgroundTask$1.run(Utils.kt:131)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:932)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by RAM237** [comment]
Same here

**Comment by LuckyClover1** [comment]
+1

**Comment by finviman** [comment]
+1

**Comment by ArunOnCloud** [comment]
+1
