### ISSUE TITLE
Error on IntelliJ 2023.2 (Community)

### ISSUE THREAD

**Issue by Itsman-AT** [Chentai-Kao/call-graph-plugin#28]
If I start to create a caller graph, I get this error message on IntelliJ 2023.2:

`java.util.ServiceConfigurationError: org.apache.logging.log4j.util.PropertySource: org.apache.logging.log4j.util.EnvironmentPropertySource not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at org.apache.logging.log4j.util.PropertiesUtil$Environment.<init>(PropertiesUtil.java:319)
	at org.apache.logging.log4j.util.PropertiesUtil$Environment.<init>(PropertiesUtil.java:310)
	at org.apache.logging.log4j.util.PropertiesUtil.<init>(PropertiesUtil.java:69)
	at org.apache.logging.log4j.util.PropertiesUtil.<clinit>(PropertiesUtil.java:49)
	at org.apache.logging.log4j.util.LoaderUtil.isIgnoreTccl(LoaderUtil.java:259)
	at org.apache.logging.log4j.util.LoaderUtil.loadClass(LoaderUtil.java:162)
	at org.apache.logging.log4j.util.StackLocator.<clinit>(StackLocator.java:64)
	at org.apache.logging.log4j.util.StackLocatorUtil.<clinit>(StackLocatorUtil.java:28)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:42)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at guru.nidi.graphviz.engine.AbstractGraphvizEngine.<clinit>(AbstractGraphvizEngine.java:24)
	at guru.nidi.graphviz.engine.Graphviz.useDefaultEngines(Graphviz.java:52)
	at guru.nidi.graphviz.engine.Graphviz.getEngine(Graphviz.java:93)
	at guru.nidi.graphviz.engine.Graphviz.execute(Graphviz.java:184)
	at guru.nidi.graphviz.engine.Renderer.toString(Renderer.java:46)
	at callgraph.Utils.getLayoutFromGraphViz(Utils.kt:300)
	at callgraph.Utils.layout(Utils.kt:115)
	at callgraph.CanvasBuilder.buildGraph(CanvasBuilder.kt:39)
	at callgraph.CanvasBuilder.build(CanvasBuilder.kt:27)
	at callgraph.CallGraphToolWindow$run$1.run(CallGraphToolWindow.kt:217)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
`

**Comment by HadesDX** [comment]
same issue:

IntelliJ IDEA 2023.2.1 (Community Edition)
Build #IC-232.9559.62, built on August 22, 2023
Runtime version: 17.0.8+7-b1000.8 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4056M
Cores: 12
Non-Bundled Plugins:
    com.kn.diagrams.generator.generator (2022.2.0)
    google-java-format (1.17.0.0)
    call-graph (0.1.17)
    Lombook Plugin (232.9559.34)

Kotlin: 232-1.9.0-IJ9559.62

**Comment by jinceon** [comment]
https://plugins.jetbrains.com/plugin/23068-call-graph-2023/


source code is https://github.com/jinceon/call-graph-plugin
I forked this project and update dependencies to make compatible with 2023.

**Comment by NiC0x36** [comment]
> https://plugins.jetbrains.com/plugin/23068-call-graph-2023/
> 
> source code is https://github.com/jinceon/call-graph-plugin I forked this project and update dependencies to make compatible with 2023.

Thanks for the heads up. According to the Plugin Website, the plugin does not support the current IntelliJ IDEA Version 2023.2.5. Is it possible to make that happen? Thanks.

EDIT: I cloned your fork and was able to fix it, I also added the https://github.com/Chentai-Kao/call-graph-plugin/pull/19 PR. I will fork it anbd make a PR myself on your repo, when I have time again.

**Comment by jinceon** [comment]
> > https://plugins.jetbrains.com/plugin/23068-call-graph-2023/
> > source code is https://github.com/jinceon/call-graph-plugin I forked this project and update dependencies to make compatible with 2023.
> 
> Thanks for the heads up. According to the Plugin Website, the plugin does not support the current IntelliJ IDEA Version 2023.2.5. Is it possible to make that happen? Thanks.
> 
> EDIT: I cloned your fork and was able to fix it, I also added the #19 PR. I will fork it anbd make a PR myself on your repo, when I have time again.

yesterday I already update the  Compatibility  range

**Comment by NiC0x36** [comment]
> 
> yesterday I already update the Compatibility range

Thanks a lot, much appreciated @jinceon! 🙏

**Comment by Itsman-AT** [comment]
Thanks, I will test it soon.
